openapi: 3.0.0
info:
  title: Infrastructure Control API
  version: 0.0.1
paths:
  /restart:
    post:
      operationId: restart
      summary: Restart infrastructure services
      tags:
        - infra
      responses:
        '201':
          description: Success response
          content:
            application/json:
              schema:
                $ref: 'infra-model.yaml#/schemas/RestartedResponse'
