openapi: 3.0.0
info:
  title: Task API
  version: 0.0.1
  description: Task API provides basic means for task management.
  contact:
    name: Anonymous
    email: none@nowhere
    url: https://black32167.github.io/social_api
  license:
    name: MIT license
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://task.example.com/v1
    description: Task tracker server
security:
  - basicAuth: []
  - bearerAuth: []
components:
  securitySchemes:
    basicAuth:
      $ref: '../security.yaml#/securitySchemes/basicAuth'
    bearerAuth:
      $ref: '../security.yaml#/securitySchemes/bearerAuth'
paths:
  /task:
    get:
      operationId: getTasks
      summary: Returns a list of tasks.
      tags:
        - task
      parameters:
        - in: query
          name: filter
          schema:
            type: string
      responses:
        '200':    # status code
          description: list of tasks
          content:
            application/json:
              schema:
                $ref: 'task-model.yaml#/schemas/Tasks'
    post:
      operationId: createTask
      summary: Creates task
      tags:
        - task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'task-model.yaml#/schemas/Task'
            example:
              title: Build the spaceship
              creatoe: John
              assignee: Jane
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: 'task-model.yaml#/schemas/Task'
  /task/{taskId}:
    get:
      operationId: getTask
      summary: Returns a task.
      tags:
        - task
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: task identifier
      responses:
        '200':    # status code
          description: task
          content:
            application/json:
              schema:
                $ref: 'task-model.yaml#/schemas/Task'
