openapi: 3.0.0
info:
  title: Administrative Control API
  version: 0.0.1
  description: Administrative API provides way to control whole infrastructure behavior.
  contact:
    name: Anonymous
    email: none@nowhere
    url: https://black32167.github.io/social_api
  license:
    name: MIT license
    url: https://opensource.org/licenses/MIT
paths:
  /restart:
    post:
      operationId: restart
      summary: Restart infrastructure services
      tags:
        - admin
      responses:
        '201':
          description: Success response
          content:
            application/json:
              schema:
                $ref: 'admin-model.yaml#/schemas/RestartedResponse'
