openapi: 3.0.0
info:
  title: Mock Server Control API
  version: 0.0.1
servers:
  - url: http://task.example.com/v1
    description: Mock server control api
paths:
  /reset:
    post:
      summary: Reset mocks
      tags:
        - mocks
      responses:
        '204':
