openapi: 3.0.0
info:
  title: Task API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://task.example.com/v1
    description: Task tracker server
paths:
  /tasks:
    get:
      summary: Returns a list of tasks.
      description:Returns task list.
      tags:
        - task
      responses:
        '200':    # status code
          description: list of tasks
          content:
            application/json:
              schema:
                $ref: 'model.yaml#/schemas/Tasks'
  /task:
    get:
      summary: Returns a task.
      description: Returns an individual task.
      tags:
        - task
      responses:
        '200':    # status code
          description: task
          content:
            application/json:
              schema:
                $ref: 'model.yaml#/schemas/Task'
